plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pureweb.browser'
    compileSdk 34

    defaultConfig {
        applicationId "com.pureweb.browser"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // GeckoView লাইব্রেরি (এটি ব্রাউজারের ইঞ্জিন)
    implementation "org.mozilla.geckoview:geckoview:124.0.20240226164122"

    // Android UI কম্পোনেন্ট
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    
    // কার্ডভিউ লেআউটের জন্য
    implementation 'androidx.cardview:cardview:1.0.0'
}