plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pureweb.browser'
    compileSdk 36

    defaultConfig {
        applicationId "com.pureweb.browser"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    splits {
        abi {
            enable true
            reset()
            include(
                    "arm64-v8a",
                    "armeabi-v7a",
                    "x86",
                    "x86_64"
            )

            universalApk false
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation("org.mozilla.geckoview:geckoview:147.0.20260212191108")
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.cardview:cardview:1.0.0'

    implementation 'com.github.bumptech.glide:glide:4.15.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.15.1'

    // ExoPlayer
    implementation 'androidx.media3:media3-exoplayer:1.3.1'
    implementation 'androidx.media3:media3-exoplayer-hls:1.3.1'
    implementation 'androidx.media3:media3-ui:1.3.1'
}